### ISSUE TITLE
What about the redis?

### ISSUE THREAD

**Issue by q10242** [nahidulhasan/laravel-docker-k8s#2]
If I wanna use redis.
is this correct?
kubectl apply -f deploy/redis/redis-master-deployment.yaml

kubectl apply -f deploy/redis/redis-service.yaml

kubectl apply -f deploy/redis/redis-slave-deployment.yaml

**Comment by nahidulhasan** [comment]
Yes, Above commands are correct.
If you need more info, you can follow this  link 
https://kubernetes.io/docs/tutorials/stateless-application/guestbook/
